---
version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # extends:
    #   file: docker-compose.yml
    #   service: app
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - ./app:/app
    env_file: .env
    # ports:
      # - 8080:8080
    depends_on:
      - db

  caddy:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
