---
version: '3.2'
services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s 

  app:
    image: shlyapnikovan/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    command: npm test
    depends_on: 
      db: 
        condition: service_healthy

volumes:
  pgdata:
