---
version: '3.2'
services:
  db:
    image: postgres:16
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: 127.0.0.1
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: shlyapnikovan/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on: 
      - db

volumes:
  pgdata:
