---
version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # extends:
    #   file: docker-compose.yml
    #   service: app
    command: npm run dev
    volumes:
      - ./app:/app
    # ports:
      # - 8080:8080

  webserver:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app
