name: push

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_NAME: shlyapnikovan/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:cached

      - name: Check
        run: make test

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest

